In [1]:
import pandas as pd
import numpy as np
import scipy.io as scio
import pickle

In [2]:
path = '../data/data_raw_pickled/subject_6_mat_dict.pickle'

In [4]:
with open(path, "rb") as input_file:
    mat_dict = pickle.load(input_file)

In [13]:
for key in mat_dict:
    print(key, mat_dict[key].shape)

periods (1, 1)
timelists_names (1, 1)
stimulus_key_raw (1, 4000)
cell_XYZ (93975, 3)
anat_stack (2048, 1188, 29)
frame_per_sec (1, 1)
behavior_raw (5, 4000)
num_cells (1, 1)
cell_XYZ_norm (93975, 3)
IX_inval_anat (1437, 1)
anat_yx (2048, 1188, 3)
anat_yz (2048, 29, 3)
anat_xz (29, 1188, 3)
timelists (1, 1)
stim_full (1, 3780)
stim_avr (1, 140)
behavior_full (5, 3780)
behavior_avr (5, 140)
behavior_full_motor (2, 3780)
behavior_avr_motor (2, 140)
eye_full_motorseed (2, 3780)
eye_avr_motorseed (2, 140)
eye_full (2, 3780)
eye_avr (2, 140)


In [14]:
print(mat_dict['cell_XYZ'])
print(mat_dict['cell_XYZ'].shape)

x, y, z = mat_dict['cell_XYZ'].max(axis=0)
print('xmax', x)
print('ymax', y)
print('zmax', z)

x, y, z = mat_dict['cell_XYZ'].min(axis=0)
print('xmin', x)
print('ymin', y)
print('zmin', z)

print('Therefore, concluded that this is a list of all of the neurons and their corresponding X,Y, and Z values')

[[ 997 1133    1]
 [ 960 1132    1]
 [ 972 1132    1]
 ...
 [1023  337   29]
 [1014  333   29]
 [1003  324   29]]
(93975, 3)
xmax 2048
ymax 1171
zmax 29
xmin 1
ymin 3
zmin 1
Therefore, concluded that this is a list of all of the neurons and their corresponding X,Y, and Z values


In [16]:
print(mat_dict['cell_XYZ_norm'])
print(mat_dict['cell_XYZ_norm'].shape)

x, y, z = mat_dict['cell_XYZ_norm'].max(axis=0)
print('xmax', x)
print('ymax', y)
print('zmax', z)

x, y, z = mat_dict['cell_XYZ_norm'].min(axis=0)
print('xmin', x)
print('ymin', y)
print('zmin', z)

[[587 579  43]
 [572 577  43]
 [577 578  43]
 ...
 [618 179 129]
 [613 177 128]
 [608 173 128]]
(93975, 3)
xmax 982
ymax 598
zmax 137
xmin 113
ymin 16
zmin 23


In [20]:
print(mat_dict['anat_stack'])
print(mat_dict['anat_stack'].shape)
print(mat_dict['anat_stack'].max())
print(mat_dict['anat_stack'].min())

[[[101 101 100 ... 100 100 100]
  [100  99 100 ...  99  99  99]
  [100 100 100 ...  99  99 100]
  ...
  [ 99  99  99 ...  99  99  99]
  [ 99  99  99 ...  99  99  99]
  [ 98  98  98 ...  99  98  98]]

 [[101 100 100 ... 100 100 100]
  [ 99  99  99 ...  99  99  99]
  [ 99  99  99 ...  99  99  99]
  ...
  [ 99  99  99 ...  99  99  99]
  [ 99  99  99 ...  99  99  99]
  [ 99  99  99 ...  99  99  99]]

 [[ 99  98  98 ...  99  98  98]
  [ 99  99  99 ...  99  99  99]
  [ 99  99  99 ...  99  99  99]
  ...
  [ 99  99  99 ...  99  99  99]
  [100 100 100 ...  99 100 100]
  [ 98  98  98 ...  99  98  98]]

 ...

 [[102 102 101 ... 100 101 101]
  [101 100 100 ... 100 100 100]
  [100 100  99 ...  99  99  99]
  ...
  [100 100  99 ...  99  99  99]
  [ 98  98  98 ...  98  98  98]
  [100  99  99 ...  99  99  99]]

 [[101 100 100 ... 100 100 100]
  [100 100  99 ...  99  99  99]
  [100  99  99 ...  99  99  99]
  ...
  [101 101 100 ... 100 100 100]
  [100 100 100 ...  99  99  99]
  [100 100 100 ... 100 100 1

In [21]:
print(mat_dict['anat_yz'])
print(mat_dict['anat_yz'].shape)
print(mat_dict['anat_yz'].max())
print(mat_dict['anat_yz'].min())

[[[0.46540881 0.46540881 0.46540881]
  [0.33333333 0.33333333 0.33333333]
  [0.59748428 0.59748428 0.59748428]
  ...
  [0.25157233 0.25157233 0.25157233]
  [0.08176101 0.08176101 0.08176101]
  [0.00628931 0.00628931 0.00628931]]

 [[0.49685535 0.49685535 0.49685535]
  [0.35849057 0.35849057 0.35849057]
  [0.60377358 0.60377358 0.60377358]
  ...
  [0.24528302 0.24528302 0.24528302]
  [0.08805031 0.08805031 0.08805031]
  [0.00628931 0.00628931 0.00628931]]

 [[0.47798742 0.47798742 0.47798742]
  [0.36477987 0.36477987 0.36477987]
  [0.59119497 0.59119497 0.59119497]
  ...
  [0.1572327  0.1572327  0.1572327 ]
  [0.08176101 0.08176101 0.08176101]
  [0.01257862 0.01257862 0.01257862]]

 ...

 [[0.11320755 0.11320755 0.11320755]
  [0.08805031 0.08805031 0.08805031]
  [0.10062893 0.10062893 0.10062893]
  ...
  [0.50314465 0.50314465 0.50314465]
  [0.63522013 0.63522013 0.63522013]
  [0.43396226 0.43396226 0.43396226]]

 [[0.14465409 0.14465409 0.14465409]
  [0.08176101 0.08176101 0.08176101]


In [23]:
print(mat_dict['timelists_names'])

[[array(['phototaxis'], dtype='<U10')]]


In [1]:
path = '../data/data_raw_pickled/subject_6_CellResp.pickle'
with open(path, "rb") as input_file:
    cellResp = pickle.load(input_file)

NameError: name 'pickle' is not defined

In [25]:
cellResp

0         1         2         3         4         5         6      \
0     0.069322  0.094509 -0.038837  0.123340  0.043918 -0.027058  0.059631   
1     0.115872  0.135311  0.054507  0.062095  0.009788  0.038441  0.052924   
2     0.024324  0.035796  0.104025  0.041190  0.026141  0.068351  0.059620   
3     0.060367  0.115756  0.130922  0.035226  0.006858  0.058401 -0.035889   
4     0.055881  0.026029  0.123885  0.102479  0.027667  0.112515  0.069663   
...        ...       ...       ...       ...       ...       ...       ...   
3775  0.000108  0.077294  0.094686 -0.013094  0.072542 -0.000776  0.051762   
3776  0.019250  0.087504  0.001916  0.094944  0.023091  0.086301  0.124138   
3777  0.116493  0.026324  0.085312  0.002587  0.029495  0.000754  0.036947   
3778  0.220887 -0.019722  0.047346  0.051595 -0.000664  0.034126 -0.025811   
3779  0.150359  0.120602  0.146342  0.035174  0.075077  0.025599  0.106551   

         7         8         9      ...     92528     92529     92530  \
0     0.119958 -0.000822  0.142400  ...  0.012632  0.123962 -0.009099   
1     0.019188  0.107125  0.033884  ...  0.090229  0.041118  0.051133   
2     0.132978  0.027799  0.052225  ... -0.000870 -0.031224  0.056552   
3    -0.060446  0.006996  0.066337  ... -0.029551  0.124942  0.008998   
4     0.038716  0.008302  0.090317  ... -0.022806  0.086411  0.063737   
...        ...       ...       ...  ...       ...       ...       ...   
3775  0.074512  0.101246 -0.001635  ...  0.099962  0.100394  0.151156   
3776  0.091221  0.138383  0.126898  ...  0.056569  0.092921  0.058905   
3777  0.082878  0.060148  0.013341  ...  0.141676  0.064139  0.099174   
3778  0.069554  0.052487  0.066253  ...  0.039629 -0.046174 -0.007159   
3779  0.165462  0.091507  0.160705  ... -0.002548  0.022574  0.131648   

         92531     92532     92533     92534     92535     92536     92537  
0    -0.022578  0.021773  0.166579  0.026144  0.073680 -0.029447 -0.000706  
1     0.139843  0.112925  0.017371  0.105643  0.050273  0.052612  0.085885  
2     0.061730  0.053769  0.073680  0.121484  0.001715  0.106162  0.225128  
3    -0.090064  0.050345  0.156501  0.041857 -0.029407  0.127859  0.202971  
4     0.135529 -0.064527  0.033825  0.057699  0.018803  0.049000  0.009254  
...        ...       ...       ...       ...       ...       ...       ...  
3775  0.078991  0.039113  0.044969  0.088002  0.077608  0.080622  0.018901  
3776  0.050022  0.015198  0.096118  0.116472  0.094572  0.031642  0.147158  
3777  0.079096  0.024979  0.134467  0.033782  0.005018  0.042288  0.067726  
3778  0.035930 -0.049079  0.097051  0.062088  0.025608  0.010954  0.113265  
3779  0.055532  0.216054  0.062201  0.129661  0.029314 -0.052840  0.147184  

[3780 rows x 92538 columns]

In [29]:
mat_dict['stim_full']

array([[3, 3, 3, ..., 2, 2, 2]], dtype=uint8)

In [33]:
mat_dict['behavior_full']

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01080417, 0.01080417, 0.01080417, ..., 0.01080417, 0.01080417,
        0.01080417],
       [0.05451683, 0.05916703, 0.04020896, ..., 0.02517741, 0.03424281,
        0.01622986],
       [0.03972838, 0.04362908, 0.05858973, ..., 0.01939605, 0.03354031,
        0.02088514]])

In [34]:
mat_dict['behavior_full_motor']

array([[ 1.84308136,  1.5336988 ,  1.08532   , ...,  0.51290619,
         2.85534954,  2.17209148],
       [-0.42269856, -0.27249229, -0.38786596, ..., -0.305136  ,
        -0.32027954, -0.57230341]])